import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Block from '../components/Block'

export default function Home() {
  const blocks = [
    new Array(8).fill(8),
    new Array(8).fill(8),
    new Array(8).fill(8),
    new Array(8).fill(8),
    new Array(8).fill(8),
    new Array(8).fill(8),
    new Array(8).fill(8),
    new Array(8).fill(8),
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Tabuleiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        { blocks.map((row, indexRow) => {
          return row.map((column, indexColumn) => {
            return <Block row={indexRow} column={indexColumn} />
          })
        }) }
      </main>
    </div>
  )
}
